### ISSUE TITLE
sheetmetalcalc.py should be its own individual project.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/learn_python#1]
@hitblast

Ideas?  It's full of  commented pseudocode with some math.

**Comment by AbbasSalloum** [comment]
Yeah sure it can be

**Comment by gbowne1** [comment]
@AbbasSalloum 

I wanted it to do plenty of related things so I think its worth doing a whole program.. not just a single .py

**Comment by hitblast** [comment]
> @hitblast
> 
> Ideas? It's full of commented pseudocode with some math.

Can be added for sure.

**Comment by gbowne1** [comment]
@hitblast  

My problem being is I know the math, just not the Python so inteded to use this to learn Python

I was gonna try this in C++ too but got stuck.

**Comment by gbowne1** [comment]
so.. make a module or a package?

**Comment by hitblast** [comment]
> so.. make a module or a package?

Module, I guess.

**Comment by Harmionee** [comment]
can I work on this ?

**Comment by gbowne1** [comment]
@Harmionee 

sure but I am going to make this its own project repository.

**Comment by gbowne1** [comment]
@Harmionee 

sure but I am going to make this its own project repository.

https://github.com/gbowne1/sheetmetal-calc
