### ISSUE TITLE
Add a tonnage calculator for forming/bending 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/learn_python#9]
Add a Bending force tonnage calculator

One formula that can be used is T = P x Th x C
where:
T = Pressure required in tons
P = Perimeter of blank in inches
Th = Thickness of material
C = Constant (see common ones below)
Constant = The material shear strength/2000 pounds

**Comment by Vicky3301** [comment]
can i work on this

**Comment by gbowne1** [comment]
Ok @Vicky3301
